### ISSUE TITLE
design_to_list is nonsense

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/paradox#115]
either we do this wizh basic R or this is should be a general helper function

in e.g. mlr3misc

**Comment by berndbischl** [comment]
Agreed. Put it in mlr3misc?

**Comment by mllg** [comment]
Now we have a name clash between mlr3misc::transpose() and data.table::transpose()... 

:cry:

**Comment by berndbischl** [comment]
well nameclashes happen? this would happen if we use datatable and purr together? 
and the solution is always the same? selective imports / explict package:method calls?
