### ISSUE TITLE
ParamSet:check should return error msg, as checkmare function

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/paradox#118]
must also be unit tested

i think currently we return a bool, that should be done by the "test" function

**Comment by jakob-r** [comment]
It behaves as in checkmate:

check: returns TRUE or String with information why it's not true
assert: TRUE or error with above defined string
test: TRUE/FALSE

mostly check dispatches to a checkmate::check* function.

It was badly documented [here](https://github.com/mlr-org/paradox/blob/14856d147e716cc0fe803e5103e7a4377a119734/R/ParamSet.R#L73)

**Comment by berndbischl** [comment]
yes, understood. i currently might have implemented this wrongly , for ParamSets, just for time reasons.

**Comment by berndbischl** [comment]
fixed and testes
