### ISSUE TITLE
Fixing params to values / parvals in paramset

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/paradox#131]
First post: Jakob tried to implement a way to "fix" a param to a certain value. This seems like a nice feature, to have constant-value params in the set, and would also help with subsetting, when a removed param would still be needed in dependencies / or a trafo function. In this case we could leave that param in the set and simply put it to a constant value.

But: The implementation sucked. We tried to do this with e.g. changing constraints so that only one value was possible (lower = upper, for dbls). But this changes too many things at once / behavior of ABS, and a dbl is really not a constant value. 

We also dicussed other options, like having a "Fixed" subclass for every params (sucks?) and other stuff.

--> I removed it for now.

The only option that seems elegant to me, is to either have in ParamSet a dict, that maps some params to constant values (and therefore extends the definition of the param in the set), or to have one "value" slot per param.

**Comment by berndbischl** [comment]
Second post: Indepently of this, I thought about marrying "paramset" and "parvals", as used in mlr3. The set and the list belong together anyway. Then an AB "<-vals" could directly be implemented in the PS, do arg checks, and so on. And this would also give us what we want from the first post?

**Comment by berndbischl** [comment]
if we implement this, we also have to think about how to handle fixed params in the trafo function

**Comment by jakob-r** [comment]
So in the second post you are suggesting to always use it like that?
```r
ps$vals = parvals
ps$vals = union(ps$vals, parvals)
ps$check()
```
?

What I don't like is the way it would work when you have a set of many parvals that you want to work with on one parset.

**Comment by berndbischl** [comment]
i dont get what you mean. 
it would simply be used like this

ps$par_vals = list(a = 1, b = 2)

which is EXACTLY the same way as we currently use it in mlr3. the only difference is that the list "parvals" is stored inside of the paramset, and the paramset knows about it, instead of us storing it independently of the set. 





> What I don't like is the way it would work when you have a set of many parvals that you want to work with on one parset.

i really dont get this last sentence at all, can you please post an example or a clarification?

**Comment by jakob-r** [comment]
So if I store a single par_vals setting in the param set, how do I store multiple par_vals (e.g. a design). 

If you embrace the fact that one par_vals setting belongs to a par_set the way you mentioned it the consequent workflow would be like the following:
Imagine I want to trafo a set of par_vals
```r
for (i in seq_along(set_of_par_vals)) {
  ps$par_vals = set_of_par_vals[[i]]
  set_of_par_vals[[i]] = ps$par_vals_trafoed #active binding
}
```
?
This would be ugly. So in the consequence, when you say that a par_vals setting belongs to a parset you also have to acknowledge that a mutliple par_vals can belong to a par_set so that the above operation is not necessary

Now, what if we have multiple designs (e.g. grid design and random design) of the same par_set how to handle them. At least now we have to store them externally anyways. That's why I would store them externally all the time because it's difficult to draw the line otherwise.

**Comment by berndbischl** [comment]
> So if I store a single par_vals setting in the param set, how do I store multiple par_vals (e.g. a design).

you dont. just because I propose A I dont have to do B? That's 2 totally different things? 
The param set specifies the param space of a certain algorithm. that algorithm has also a certain current configuration. A design, optpath, whatever has nothing to do with this?



> , when you say that a par_vals setting belongs to a parset you also have to acknowledge 

no i certainly dont have to do that?

**Comment by berndbischl** [comment]
PR is here #167
branch is pvinps

**Comment by berndbischl** [comment]
what we now need to take care of
- subsetting
- design generation
- sampling
