### ISSUE TITLE
ParamSet: remove convenience acessors ?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/paradox#135]
at the moment we have this 
```
    class = function() private$get_member_with_idnames("class", as.character),
    lower = function() private$get_member_with_idnames("lower", as.double),
    upper = function() private$get_member_with_idnames("upper", as.double),
    values = function() private$get_member_with_idnames("values", as.list),
    nlevels = function() private$get_member_with_idnames("nlevels", as.double),
    is_bounded = function() all(map_lgl(self$params, "is_bounded")),
    special_vals = function() private$get_member_with_idnames("special_vals", as.list),
    defaults = function() Filter(is_proper_default, private$get_member_with_idnames("default", as.list)),
    tags = function() private$get_member_with_idnames("tags", as.list),
    storage_type = function() private$get_member_with_idnames("storage_type", as.character),
```

all of that could be removed, as we have 

as.data.table(param_set)

i am pretty unsure here. i would like to make the API smaller. 

the 2 downsides are:

a) we now always would have to write
as.data.table(ps)$lower 
instead of
ps$lower

b) 
creating the whole dt is a bit slower i guess? when we only need one element

@mllg opinion?

**Comment by berndbischl** [comment]
> I doubt that all of these accessors are actually needed. Can you give examples why you would want the special values for **all** parameters? Or the number of levels?

But does it help that much if I remove only SOME?
Isnt that then really inconsistent?

Ok, let's make a list what is less useful
- special_vals
- nlevels
- is_bounded - because you can subset to bounded stuff already with ids()?
- values?

what do we really need:
- lower, upper
- defaults

unsure:
- storage_type?
- tags?


> Oh, and a function which returns the parameter ids for a given tag.
huh? ps$ids(tags = "foo") was just implemented. *you* asked for that...

#127

**Comment by mllg** [comment]
> But does it help that much if I remove only SOME?
> Isnt that then really inconsistent?

So you want to write a getter for everything, just for consistency?



> huh? ps$ids(tags = "foo") was just implemented. _you_ asked for that...

Great, thx!

**Comment by berndbischl** [comment]
> > 
> 
> So you want to write a getter for everything, just for consistency?

well, i made the list below... I guess you are right

**Comment by berndbischl** [comment]
i will fade quite a few out, we can simply add them when it becomes apparent.
i guess that was the policy anyway

**Comment by mllg** [comment]
:+1:

**Comment by berndbischl** [comment]
you asked:

> Or the number of levels?

it is used in generate_design_grid.

all of the other are also used / or i can easilly imagine usecases. and at some point consistency does matter, yes, 

i dont know if it is valuable to waste more time to operate these simple functions out.
they will stay.
