### ISSUE TITLE
shorthand notation for paramsets - the general issue

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/paradox#156]
1) our current way of specifying params is very verbose. something shorter might be useful for applications.

2) the PCS format might be a nice idea. it is string based, and we could even parse PCS files if we implement a parser

it is defined here:
http://aclib.net/cssc2014/pcs-format.pdf

3) i made quite a lot of progress my writing my parser with the rly package
a PR is here #155

**Comment by berndbischl** [comment]
if we finish this, we should also allow to export sets to PCS string format

**Comment by mb706** [comment]
There is also [this](https://mlrcpo.mlr-org.com/reference/pSS.html#examples).

**Comment by mb706** [comment]
closed by #301 (i.e. ps() shortcuts)?

**Comment by be-marc** [comment]
> closed by #301 (i.e. ps() shortcuts)?

Yes
