### ISSUE TITLE
createCollectionParamSet is a bad name

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/paradox#16]
probably repParam is better.

one could also think about rep.Param, and implement a new S3 method, but as the id is changed this kindof a violation of the fact that R in other cases simply copies the object?

or call it vectorizeParam

**Comment by jakob-r** [comment]
`vectorizeParam` is bad because the simple repetition does not create a vector.

I opted for `repeatParam` and `trafoOnRepeatedParam`. For a function that will be less often used we can be a bit more verbose.
