### ISSUE TITLE
trafo on design

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/paradox#161]
currently it has do be done like that
```r
d1 = generate_design_grid(ps, resolution = 4)
dd1 = d1$data
d2 = ps$trafo(dd1)
```
(taken from test_trafo.R)

Can it become
```r
d1 = generate_design_grid(ps, resolution = 4)
d2 = ps$trafo(d1)
```
or
```r
d1 = generate_design_grid(ps, resolution = 4)
d2 = d1$data_transformed #or similar
```

**Comment by berndbischl** [comment]
could you argue please why?

**Comment by berndbischl** [comment]
ah, also you are slightly wrong

you can do this

```
d1 = generate_design_grid(ps, resolution = 4)
d1$transpose(trafo = TRUE)
```

**Comment by berndbischl** [comment]
thats the "idiom" you should use

**Comment by jakob-r** [comment]
ok - than it is a bit more intuitive. i am okay with that

**Comment by berndbischl** [comment]
> ok - than it is a bit more intuitive. i am okay with that

a) must be visble in vignette

b) you can rbindlist to get a dt
