### ISSUE TITLE
Allow custom `.check` function in ParamUty

### ISSUE THREAD

**Issue by mb706** [mlr-org/paradox#165]
ParamUty is used for parameters that do not fit any of the other basic categories, e.g. a functional parameter. It would be useful if one could specify the requirements of this parameter for basic typechecking when `ParamSet$assert()` is called. This could be achieved letting the `.check` function be something custom, either by making it public / an active binding, or by setting it in the constructor.

**Comment by berndbischl** [comment]
you got it, please try it and check if it suffices
