### ISSUE TITLE
generate_design_grid should allow both resolution and param_resolution argument

### ISSUE THREAD

**Issue by mb706** [mlr-org/paradox#170]
The use-case for `param_resolution` is probably that a user wants a certain resolution for most parameters except for one or two. It would be easier if he could enter this as
```r
generate_design_grid(ps, resolution = 10, param_resolution = c(lowres1 = 2, lowres2 = 3))
```

**Comment by berndbischl** [comment]
That's just sugar and has very low prio

**Comment by berndbischl** [comment]
done and tested
