### ISSUE TITLE
Maybe Sampler1DTruncNorm should allow unbounded parameters

### ISSUE THREAD

**Issue by mb706** [mlr-org/paradox#171]
I think it would be reasonable to allow unbounded parameters in `Sampler1DTruncNorm` (to get a half-truncated or non-truncated normal distribution); `mean` and `sd` would need to be set manually, however.

**Comment by mb706** [comment]
(Applies to Sampler1DRfun in general)

**Comment by berndbischl** [comment]
> (Applies to Sampler1DRfun in general)

for Sampler1DRfun this works without changes?

```
p = ParamDbl$new("x")
ps = ParamSet$new(list(p))
s = Sampler1DRfun$new(param = p, rfun = function(n) rnorm(n, mean = 1, sd = 1))
d = s$sample(3)
print(d)

```

**Comment by berndbischl** [comment]
1d sampling / normal is now also allowed for unbounded params
