### ISSUE TITLE
SamplerHierarchical is misspelled

### ISSUE THREAD

**Issue by mb706** [mlr-org/paradox#173]
`SamplerHierachical` -> `SamplerHierarchical` (and possibly other similar corrections)

**Comment by berndbischl** [comment]
> and possibly other similar corrections

what does this mean?

**Comment by berndbischl** [comment]
thx done

**Comment by mb706** [comment]
>> and possibly other similar corrections
>
> what does this mean?

I wasn't sure if there would be other places (references in the text for example) that have the same misspelling.

---

I think the filename of `R/SamplerHierachical.R` should also be corrected now.

**Comment by berndbischl** [comment]
> think the filename of `R/SamplerHierachical.R` should also be corrected now

fixed
