### ISSUE TITLE
No way to remove deps(?)

### ISSUE THREAD

**Issue by mb706** [mlr-org/paradox#174]
When trying to subset a ParamSet that would cut off dependencies we get the message
```
Subsetting so that dependencies on params exist which would be gone: %s.
If you still want to do that, manipulate '$deps' yourself.
```
however `$deps` is an active binding with no way of modifying the underlying `private$.deps`.

**Comment by berndbischl** [comment]
isnt the return values "$deps" a reference? so you can change that?

**Comment by mb706** [comment]
I mean, you could change the Dependency objects and make them point to other parameters, but I don't think its possible to remove them.

**Comment by berndbischl** [comment]
AB "deps" is now not read-only any-more but settable
