### ISSUE TITLE
What stops us from having dependencies on non-discrete parameters?

### ISSUE THREAD

**Issue by mb706** [mlr-org/paradox#175]
The `Dependency` base-class checks that a dependee-param is `ParamFct` or `ParamLgl`. While it makes sense that a parameter is not `Dbl` for the `Condition`s available so far, why shouldn't something be dependent on an integer parameter being 0, or a newly defined CondInequality making something depend on a `Dbl` being positive?

**Comment by berndbischl** [comment]
I guess we can relax this

**Comment by berndbischl** [comment]
i reomved the type check in the dependency and added a unit test for depending on an int
