### ISSUE TITLE
Design$transpose(trafo = TRUE) should work when no trafo function is present

### ISSUE THREAD

**Issue by mb706** [mlr-org/paradox#177]
There should be a way to "transpose" a design and receive values in the form that they were intended: trafo'd if a `$trafo` function is present, untrafo'd otherwise. I would remove the error if no trafo function is present and `trafo = TRUE`; other ways would be to have a trafo = "maybe" option or something like that.

I would furthermore make `trafo = TRUE` the default in `$transpose`.

**Comment by berndbischl** [comment]
did what you requested
