### ISSUE TITLE
ParamSetCollection only allows setting some of the param vals

### ISSUE THREAD

**Issue by mb706** [mlr-org/paradox#205]
Problem seems to be the code that detects the possible member of set_ids in the `param_vals` AB code. (It should probably be extracted using something like `map(private$.sets, "set_id")` anyways to react to changes in param set set_ids)

```r
ps1 = ParamSet$new(list(ParamDbl$new("test1")))
ps1$set_id = "one"
ps2 = ParamSet$new(list(ParamDbl$new("test2")))
ps2$set_id = "two"
psx = ParamSetCollection$new(list(ps1, ps2))
psx$param_vals$one.test1 = 1
psx$param_vals$two.test2 = 2
```
The last two lines give
```r
> psx$param_vals$one.test1 = 1
> psx$param_vals$two.test2 = 2
Error in (function (xs)  : 
  Assertion on 'x' failed: Parameter 'two.test2' not available..
```

**Comment by mb706** [comment]
#206 seems to have solved this, but there should probably still be tests.

**Comment by berndbischl** [comment]
added tests
