### ISSUE TITLE
special chars should not be allowed in id

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/paradox#207]
@mllg brought this up here
https://github.com/mlr-org/paradox/pull/206

we should check that a user CANNOT enter anything weird in an id

**Comment by mb706** [comment]
Checking this in all exported functions on all things that could eventually turn into a set_id seems like a high price to pay for a regex call.

**Comment by mllg** [comment]
The regex is not the point. If you do an assertion (in the super class?), you can be sure that you can use the ids in data.table columns, file names and formulas.

**Comment by berndbischl** [comment]
> you do an assertion (in the super class?), you can be sure that you can use the ids in data.table columns, file names and formulas.

thats why i created this issue....
whats the best way to guard against this? checkmate function?

**Comment by mllg** [comment]
`assert_string(id, pattern = "^[[:alpha:]]+[[:alnum:]_.]*$")` should work...

But what if the user specifies an id with a "." in it? Your way of pasting and splitting ids does not seem to work in this case?

**Comment by berndbischl** [comment]
> `assert_string(id, pattern = "^[[:alpha:]]+[[:alnum:]_.]*$")` should work...

shouldnt something similar like this even be a helper in cm? seems pretty common case...?



> But what if the user specifies an id with a "." in it? Your way of pasting and splitting ids does not seem to work in this case?

i thought it did? the operations are this:
a) paste the setid to the param id, with a dot --> works if  setid or paramid has a dot
b) replace setid in setid.param with emptystring --> works
c) split off left most dot --> doesnt work if setid contains a dot...
hmm. c) is faulty?

**Comment by berndbischl** [comment]
i think i could change c), because that is only used when the setids and paramids are already known. 
so i could split wrt to them? hmm maybe a bit cumbersome

**Comment by berndbischl** [comment]
i would be nicer if the separating dot would be "clearer" / protected.
but i cannot disallow dots in parameter names....
i made the suggestion to use "#" as a separating char, or ":", you didnt wnat this (i guess with reason) as we now create invalid ids...

**Comment by berndbischl** [comment]
we are done here, i added helper assert_id and use this in param ids and paramset ids
