### ISSUE TITLE
Thought: Maybe dependencies should not be respected directly in feasibility check

### ISSUE THREAD

**Issue by mb706** [mlr-org/paradox#216]
Dependencies and "required" parameters interact in a suboptimal way:
```r
ps = ParamSet$new(list(
  ParamFct$new("a", c("a", "b")),
  ParamDbl$new("x", 0, 1, tags = "required")))
ps$add_dep("x", "a", CondEqual$new("a"))
```
Gives the following behaviour:
```r
> ps$check(list(a = "a", x = 1))
[1] TRUE
> ps$check(list(a = "b", x = 1))
[1] "Condition for 'x' not ok: a equal ; instead: a=b"
> ps$check(list(a = "b"))
Error: Missing required parameters: x
```
(can a parameter be `"required"` and still have a dependency? Sure, if mlr-org/mlr3pipelines#101 gets implemented, with `PipeOp`s behind a `PipeOpBranch` with parameters that may be required.)

I think it is not useful to give an error if a parameter's dependency is not satisfied. The meaning of a dependency should probably be "value is ignored if condition is not true". See my comment in mlr-org/mlr3pipelines#101. If the `dependency` should make that mlr3pipelines issue solvable, then the behaviour should probably be "if dependency is not fulfilled, then ignore the `"required"` tag".

However, it is possible that dependencies have a different meanings in other context, and that implementing it this way would make trouble elsewhere.

**Comment by berndbischl** [comment]
> (can a parameter be `"required"` and still have a dependency?

sure, pretty much: yes

**Comment by berndbischl** [comment]
> The meaning of a dependency should probably be "value is ignored if condition is not true".

problem is this: if a dependency is not satisfied, leaving the param in the list will lead to (potential) errors  when you pass the list down to algorithms you dont control which then do "the dependency check"

we can silently remove the values (instead of generating a check-error like now).
but i usually dislike this, it is much less visible and bug prone?
now, we at least (often) see if stuff goes wrong?

**Comment by berndbischl** [comment]
also, i think this latter part is another issue?

**Comment by berndbischl** [comment]
> Gives the following behaviour:

whats actually wrong here...? the messages seem ok=?

**Comment by mb706** [comment]
I guess there are two related issues here:
* A parameter that both has a dependency and a `"required"` tag will always fail a `$check` if the dependency is not satisfied, because its presence causes an error ("Condition not ok") and its absence causes an error ("Missing required parameter").
* Keeping the current behaviour (error on unsatisfied condition) will make dependencies in graphs (mlr-org/mlr3pipelines#101) very user-unfriendly. `graph$param_set$values$branch.selection = "pca"` for quick switching between paths will not work, one will always have to unset parameters for pipeops on one branch, set parameters for pipeops of another branch, and switch branching path at the same time.

**Comment by mb706** [comment]
Maybe it would be an option to ignore conditions when *setting* values; instead whatever function is used to get parameters by tag as described in #180 (let's call it `get_values`) could have an option to not return parameter values with unsatisfied condition, i.e.
> we can silently remove the values (instead of generating a check-error like now).
but i usually dislike this, it is much less visible and bug prone?
now, we at least (often) see if stuff goes wrong?

Was this a problem in `mlr` (which is more lenient with conditions)?

**Comment by mb706** [comment]
Another problem: Suppose a `ParamSet` `"ps_scale"` with one `"required"` parameter `"scale"` is with another `ParamSet` `"ps_branch"` inside a `ParamSetCollection`. There is a `ParamSetCollection`-wide condition generated by the branch: parameter `ps_scale.scale` depends on `ps_branch.selection == "scale"`.
```r
ps_scale = ParamSet$new(list(ParamLgl$new("scale", tags = "required")))
ps_scale$set_id = "ps_scale"
ps_branch = ParamSet$new(list(ParamFct$new("selection", c("scale", "pca"))))
ps_branch$set_id = "ps_branch"
pscol = ParamSetCollection$new(list(ps_branch, ps_scale))
pscol$add_dep("ps_scale.scale", "ps_branch.selection", CondEqual$new("scale"))
```
Now trying to set `ps_branch.selection` to `"pca"` will always fail: We can set it while `ps_scale.scale` is set (error because condition not satisfied), and we cannot unset it (error because "required" is ignored)
```r
pscol$values = list(ps_branch.selection = "pca", ps_scale.scale = FALSE)
#> Error in (function (xs)  :
#>   Assertion on 'x' failed: Condition for 'ps_scale.scale' not ok: ps_branch.selection equal scale; instead: ps_branch.selection=pca.
pscol$values = list(ps_branch.selection = "pca")
#> Error in (function (xs)  :
#>   Assertion on 'x' failed: Missing required parameters: ps_scale.scale.
```
This will happen *even if* we ignore the `"required"` tag whenever a condition is not satisfied: The underlying `ps_scale` `ParamSet` does not know about the condition and that it is not satisfied. Whenever the `pscol$values` gets set, the values get delegated to `ps_scale$values`, where an error will be thrown.

**Comment by be-marc** [comment]
We only check for the `require` tag when `ParamSet$get_values()` is called. So this might be solved. Reopen if you think otherwise.
