### ISSUE TITLE
"required" parameters should not give an error in $check()

### ISSUE THREAD

**Issue by mb706** [mlr-org/paradox#217]
The `ParamSet$check` function should only return a `character(1)` describing why a parameter does not fit. Instead it gives an error if a required parameter is absent:
```r
> ps = ParamSet$new(list(ParamDbl$new("x", tags = "required"), ParamDbl$new("y")))
> ps$check(list(y = 1))
Error: Missing required parameters: x
```

**Comment by berndbischl** [comment]
oops sorry
fixed
