### ISSUE TITLE
Rename ParamSetCollection $add to $add_paramset (or smth)

### ISSUE THREAD

**Issue by mb706** [mlr-org/paradox#220]
`ParamSetCollection` inherits from `ParamSet`, where the `$add` function adds a single parameter. It is bad style to overload a function during inheritance and fundamentally change its meaning.

**Comment by berndbischl** [comment]
i actually disagree here. 

> `ParamSetCollection` inherits from `ParamSet`, where the `$add` function adds a single parameter

and thats wrong? the docs clearly say "add" is BOTH for adding params and adding sets?
and for collections i now only allow one of the 2.
so i dont change meaning i just disallow partial behavort

**Comment by berndbischl** [comment]
i would like to close this, any further counterarguments?

**Comment by mb706** [comment]
>  "add" is BOTH for adding params and adding sets?

That's a good point.
