### ISSUE TITLE
Discrete Param Space with numeric values

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/paradox#228]
Is this the only way to build a discreete numeric parameter?

```r
param_set = ParamSet$new(params = list(
  ParamFct$new("num.trees", levels = c("100", "250", "500", "1000"))
))
param_set$trafo = function(x, param_set) {
  x$num.tress = as.numeric(x$num.trees)
  return(x)
}
```

**Comment by berndbischl** [comment]
short answer: yes. 

longer answer: i dislike this a little bit too, as the type of the param is then always wrong in the created datatables.

do you have a better idea? i think this possibly should not stay like this, it looks clumsy

**Comment by jakob-r** [comment]
ParamIntFct seems to be the cleanest solution

**Comment by berndbischl** [comment]
> ParamIntFct seems to be the cleanest solution

if you mean having a dedicated class, i would like to avoid this, and would like our system to handle this natively, but dont see this. so i thing this would also be my next idea.

can we define the scope? basically a categorical param where the values are numbers? and we would allow a finite list of double values which would also subsume integers?

i still struggle with the name... "ParamIntFct" i dont like.....
ParamFctNum? 
ParamFctNumbers
ParamNumericGrid?

**Comment by mb706** [comment]
The different parameter types represent different levels of information about the underlying process that is being parameterized. `ParamDbl` implies that for parameter values that are close, the resulting behaviour is usually similar (we hope it is mostly continuous, in some sense). `ParamInt` implies that there is some kind of ordering of behaviour with respect to the underlying parameter. Behaviour for value '2' is usually closer to behaviour for value '1' than for value '0'. `ParamFct` has no information about behaviour. The optimization algorithms (should) make use of this information: MBO would probably one-hot-encode `ParamFct` but not `ParamInt`. What should the semantics of `ParamFctNum` be that is not captured by this?

**Comment by jakob-r** [comment]
Good point. So the actual proposed workaround probably should look like this to represent the problem better:
```r
param_set = ParamSet$new(params = list(
  ParamInt$new("num.trees", lower = 1, upper = 4)
))
param_set$trafo = function(x, param_set) {
  x$num.tress = c(100, 250, 500, 1000)[x$num.trees]
  return(x)
}
```

**Comment by mb706** [comment]
Should we close this issue then?

**Comment by jakob-r** [comment]
Yes. Until somebody wants to reopen with new arguments?

**Comment by berndbischl** [comment]
i still fill the currenty situation is somewhat suboptimal here and would like to dicuss this at som epoint

**Comment by berndbischl** [comment]
Maybe we can have ParamEnum which allows general types of values?
at some point we decided that it would be nice to only  have atomic cols in a dt.
but mlr3 uses list-cols heavily, so maybe this is not such a big problem anymore?

**Comment by RaphaelS1** [comment]
Can `ParamUty` be extended to allow levels and lower/upper to be supplied? At first usage this was additionally how I thought it was meant to be used, i.e. to allow any value type and thus any type for levels/lower/upper

**Comment by berndbischl** [comment]
actually, we discussed the "enum" thing a bit. there are definitive advantages for having atomic types in the "untrafoed" space. we act on this space with either optimizers or ML models (in bayes opt). these methods do not like non-atomic values.

it would probably best do 

a) advice uses to do either this
int [1,2,3] --trafo--> obj1, obj2, obj3 (if there is an order)
fct ["a","b","c"] --trafo--> obj1, obj2, obj3 (if there is no order)

b) to have some sugar for the trafos, like above. this is already discussed here
#245

**Comment by berndbischl** [comment]
> Can `ParamUty` be extended to allow levels and lower/upper to be supplied? At first usage this was additionally how I thought it was meant to be used, i.e. to allow any value type and thus any type for levels/lower/upper

can you open a clean issue for this pls? maybe with 1-2 examples?

**Comment by jakob-r** [comment]
Okay I guess the issue is here: #251

**Comment by mb706** [comment]
The general consensus seems to be to close this.
