### ISSUE TITLE
Travis makes superfluous commits

### ISSUE THREAD

**Issue by mb706** [mlr-org/paradox#229]
Most of the recent travis commits are because of irrelevant changes in the documentation.

Picture:

![waste_my_time](https://user-images.githubusercontent.com/15801081/59335738-7475c300-8cfd-11e9-86d9-b3feca739beb.png)

Example: 5937fb0

This can be avoided by pushing the documentation to the gh_pages branch instead of the master branch, or by doing some [shell magic](https://github.com/mlr-org/mlrCPO/blob/4a7b3bbcdcde132fbd757995346c049f1235dc35/.travis.yml#L112-L114).

**Comment by jakob-r** [comment]
We should probably do it consistently across all mlr-org repos. @pat-s can you apply the deployment of the other packages to paradox? Would be great!

**Comment by jakob-r** [comment]
@pat-s thanks, but I think you forgot to change the github settings and to delete the docs directory. I did it now.

**Comment by pat-s** [comment]
> I think you forgot to change the github settings

That was on my list; it can only be changed after the `gh-pages` branch exists. You already did it, great!

>  delete the docs directory.

Thanks! I indeed forgot this one.
