### ISSUE TITLE
Transfer paradox vignette to mlr3book?

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/paradox#230]
We probably also want to do that, right?

**Comment by berndbischl** [comment]
yes

**Comment by jakob-r** [comment]
@mboecker could you do that?

**Comment by mboecker** [comment]
Yes, do you want me to downsize that a bit, or do you mean simple copy-paste?

**Comment by jakob-r** [comment]
Let's discuss this question in the PR.

We will close this Issue as soon as in paradox

- [ ] the vignette is removed
- [ ] a link to the mlr3book chapter is in the README
