### ISSUE TITLE
best way to return the ParamSet default if no user value is supplied

### ISSUE THREAD

**Issue by pat-s** [mlr-org/paradox#235]
Let's say we have the following ParamSet and for `diagonal` the user supplied a value during construction setting it to `TRUE`.

What is the most elegant way internally to set `diagonal` 

1. to the user supplied value (if there is one)
2. to the ParamSet default (if no user value was supplied, e.g. for `verbose`

The `value` column only exists if a user supplied a value during construction, e.g. via `param_vals`.

Intuitively I would use some if clauses but it feels that this should be handled in a more general way?

```
ParamSet: paramset
         id    class lower upper      levels     default value
1:   lambda ParamDbl     0     1             <NoDefault>      
2: diagonal ParamLgl    NA    NA  TRUE,FALSE       FALSE  TRUE
3:  verbose ParamLgl    NA    NA  TRUE,FALSE       FALSE    
```

**Comment by mb706** [comment]
You should use `param_set$values$diagonal` or, if you call a function, something like `mlr3misc::invoke(fun, param_set$values)`. The `param_set$default` is just meta-information and it is probably a bug if you use it anywhere inside the function that you are trying to parameterize.

**Comment by berndbischl** [comment]
@pat-s has that helped? to be honest i also really didnt get your question.
setting paramvalues works as martin has described.
