### ISSUE TITLE
ids() get_values() should be able to filter by tag *absent*

### ISSUE THREAD

**Issue by mb706** [mlr-org/paradox#239]
probably prefix tag with exclamation mark

**Comment by berndbischl** [comment]
Can you please post more context and info here? And is there a code example that demos the problem?

**Comment by mb706** [comment]
The `ids()` and `get_values()` functions can filter params by tags, e.g. `ps$ids(tags = "predict")` gets the ids of all parameters whose tags contain `"predict"`. There should be the possibility to get all ids that do not match a tag, e.g. `ps$ids(tags = "!predict")` could get all ids of parameters that do not have the `"predict"` tag.

@mllg do you remember the particular problem we were talking about when we came to this? We needed it for *something* but I don't remember what now.

**Comment by mllg** [comment]
> @mllg do you remember the particular problem we were talking about when we came to this? We needed it for _something_ but I don't remember what now.

Nah, I cannot remember. Closing here until this comes up again. Should be easy to implement.
