### ISSUE TITLE
Abstract classes aren't clear outside of documentation 

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/paradox#243]
This is a R6 problem: abstract classes aren't well defined, and a user problem: users don't read documentation. However for example if I do the following:

```R
ps <- ParamSet$new(list(ParamDbl$new("A")))
x <- Sampler$new(ps)
x$sample(2)
````

It isn't until the last step I get a confusing error message:
````
Error in private$.sample(n) : abstract
````

Can I suggest something like the distr6 solution, [here](https://alan-turing-institute.github.io/distr6/articles/webs/r6_and_design_patterns.html#abstract-classes)

**Comment by berndbischl** [comment]
i am happy to look at what you technically do there. but as a short comment now, our policy is basically to never discuss arguments like:

> users don't read documentation.
or
"hey maybe people are too lazy to learn R6, so lets do X for these guys"

if WE think a solution is APPROPRIATE and you cannot argue AD REM why its not, we dont change that

**Comment by RaphaelS1** [comment]
Understood completely.

A solid argument is that it isn't unreasonable for a user, as I just did myself, to try something like `Sampler$new(param)`, any well-built OO language would throw an error immediately as constructing an abstract class is meaningless.

**Comment by berndbischl** [comment]
because otherwise this leads IMHO into an infinitely deep vicious cycle straight into hell, and we are not paid to maintain software for people who dont want to read / learn stuff X (when there are good arguments that X is appropriate!). maybe Microsoft in this position, we are not

(sorry for the rant which you did not ask for i will now read you link)

**Comment by RaphaelS1** [comment]
No don't worry I completely understand your point

**Comment by berndbischl** [comment]
> any well-built OO language would throw an error immediately as constructing an abstract class is meaningless.

perfectly agree!  marking a class as "abstract"  (and then disallowing direct construction) is already n my list of "mssing R6 features"

**Comment by berndbischl** [comment]
i just think, resolving these problems shouldnt happen in paradox, but a dedicated package

**Comment by RaphaelS1** [comment]
Perhaps we should find time for a R6.5 discussion then

**Comment by mb706** [comment]
As a comment on the technical side, the initializer of the abstract class would need to check if the *abstract class* is being instantiated, or if a _subclass_ is being initialized and this subclass called `super$initialize()` (which it may do for legitimate reasons).

**Comment by RaphaelS1** [comment]
For some reason the code on the distr6 website I linked is actually shortened, in practice it looks like this:

```R
    if(getR6Class(self) == classname)
      stop(paste(classname,"is an abstract class that can't be initialized."))
```

Where `getR6Class` is a function that gets the class name from an R6 object

**Comment by mb706** [comment]
So are we closing this and waiting for R to catch up in terms of OO features?

**Comment by berndbischl** [comment]
this has nothing to with paradox, i moved this here

https://github.com/mlr-org/r6plusplus/issues/9
