### ISSUE TITLE
What is ParamSet $extra_values?

### ISSUE THREAD

**Issue by mb706** [mlr-org/paradox#244]
It is not documented anywhere as far as I can tell.

**Comment by jakob-r** [comment]
They have been introduced here:
https://github.com/mlr-org/paradox/commit/3351ba95c24e77fe9d34d2fb06053cad672ecaad
Accordingly these are the values of parameters that are not in the param set.

**Comment by berndbischl** [comment]
@mllg if you introduced this, can you please document this?
