### ISSUE TITLE
unhelpful error when calling $add_dep without a proper condition

### ISSUE THREAD

**Issue by mboecker** [mlr-org/paradox#249]
```r
ps$add_dep("order", "kernel", "besseldot")
```

this fails with the unhelpful message 

> Error in cond$test : $ operator is invalid for atomic vectors

while the correct code would be

```r
ps$add_dep("order", "kernel", CondEqual$new("besseldot"))
```

Maybe we could add a more helpful error message or just convert it to do the right thing?

**Comment by mb706** [comment]
What's missing is an `assert_r6`
