### ISSUE TITLE
ParamSet Vectorized Test for Feasability

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/paradox#25]
The expressions in the requirements are supposed to work vectorized.

However for the checkmate assert/test/check functions we only evaluate them on single values. Somehow we would like to have a TRUE/FALSE vector for a bunch of values.

**Comment by jakob-r** [comment]
We don't want it to be vecrotized because checkmate standard implies it is an atomic. However we could combine the error messages for the check and assert function of a ParamSet so that all infeasibilies can be returned.

**Comment by berndbischl** [comment]
I guess I am closing then
