### ISSUE TITLE
Check that conditions can be fulfilled

### ISSUE THREAD

**Issue by mb706** [mlr-org/paradox#252]
We could detect when someone adds a condition that can never be fulfilled, which would probably be a bug. E.g. in the following, `"c"` is not a level of `"dependor"`, so adding it as a condition to `"dependent"` should throw an error or at least a warning.
```r
ParamSet$new(list(
  ParamFct$new("dependor", levels = c("a", "b")),
  ParamLgl$new("dependent")))$
  add_dep("dependent", "dependor", CondEqual$new("c"))
```

**Comment by jakob-r** [comment]
Closing because PR has solved it.
