### ISSUE TITLE
Add a Condition for mutually exclusive parameters

### ISSUE THREAD

**Issue by mboecker** [mlr-org/paradox#254]
When you have multiple parameters to a learner that all set the same internal parameter by different means, you'd like to encode that in the parameter dependencies to ensure the user doesnt set more than one options.

For example, if a learner derives some splitting rule from either a parameter alpha or another parameter called p (which is internally calculated by say 1-alpha if you set alpha), you want to make sure that not both of these are set by the user, since p would overwrite the value passed to alpha.

What I'd like to do is `ps$add_dep("p", "alpha", CondIsNull$new())` to ensure that alpha is null, when the user chooses to set p. You would also need to set `ps$add_dep("alpha", "p", CondIsNull$new())`.

Or maybe something like `ps$add_mutually_exclusive(c("alpha", "p"))`?

**Comment by berndbischl** [comment]
Why don't you simply add a checkmate assertion / custom error message for that case?

**Comment by jakob-r** [comment]
In the case that multiple parameters mean the same just in a transformed way it is probably enough to manually check in the learner implementation as @berndbischl suggested.

In the hypothetical case that two parameters are mutually exclusive and depending on which one is set the algorithm works differently we could think about it again (or just add a imaginary categorical parameter that both depend on)

**Comment by berndbischl** [comment]
> In the hypothetical case that two parameters are mutually exclusive and depending on which one is set the algorithm works differently we could think about it again (or just add a imaginary categorical parameter that both depend on)

i dont want the latter, i think. this sounds a bit "weird"? also we really have to clearly state what we gain from an extra-mechanism here. 
pls note:
- we have already multiple ways to do arg--checks, without paradox. for "free".
- if we build structure in paradox for cases like these, pls dont simply think about arg checks. think about the other operations, too. these are much more importnant / interesting? for tuning and designs and so on. and i currently dont see how we would support anything there for the current case? and if we cant, i am not sure we should relfect it in paradox

**Comment by jakob-r** [comment]
It was just hypothetical anyways. So I doubt we should further discuss this now :slightly_smiling_face: 
Let's stay with the conclusion that in the given case argchecks in the learner implementation are the go to solution. Comments next to the Param definitions also don't hurt.

If you want to add something feel free to reopen.

**Comment by berndbischl** [comment]
@mboecker ok?
