### ISSUE TITLE
Allow tuning over ParamUty

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/paradox#255]
Application:

I want to tune over a range of values, which are neither `factor` nor `number`.

Example:
2 different architectures for `mlr3keras`.

Currently, this is impossible, as
 a) `ParamUty` does not allow a list of possible values
 b) `mlr3tuning` does not allow tuning over `ParamUty`

I guess my application is not the only case where this blocks tuning?

**Comment by pfistfl** [comment]
I  guess related to #251

**Comment by pfistfl** [comment]
Update: 

Found out that I can solve this via
```r
ps = ParamSet$new(list(ParamFct$new("model", levels = c("arch1", "arch2"), tags = "train")))
ps$trafo = function(x, param_set) {
      if (x == "arch1") x$model = architecture_1
      else  if (x == "arch2") x$model = architecture_2
      return(x)
}
```

But this should really be documented somewhere promin as people will stumble over this frequently.

**Comment by jakob-r** [comment]
Your code should not work. `x == "arch1"` should be `x$model == "arch1"`.
A more elegant solution could be:
```r
ps$trafo = function(x, param_set) {
      mapping = list(arch1 = ...)
      x$model = mapping[[x$model]]
      return(x)
}
```

**Comment by mb706** [comment]
Can also use `switch()` which may be faster if the result values require computation.
