### ISSUE TITLE
we need a function in ParamSet that checks whether a dt contains only feasible values

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/paradox#268]
we have quite a few places where we pass dt's in, and we need to assert their validity

comments: 
- in many places we seem to call Design$new(ps, dt) for that purpose. while this is not so great code, anyway, it also doesnt really do what i thought it does. it does some rudimentary assert but really doesnt check whether the rows are really feasible wrt to the PS
(we should "grep" for Design$new in mlr3tuning and paradox, maybe HB and mbo at least)

- we also need to check whether NAs occur only in the correct places (for subordinate params which are inactive). we had a bad bug, where lots of NAs occured, and then we simply filtered them out through "transpose" and the resulting vector looked valid again. such an assert would have guarded against this bug

**Comment by mb706** [comment]
> we should "grep" for Design$new

I found five instances in the codebase I happen to have checked out right now. Two of them in functions named `generate_design_...()`, one in the `Sampler` class, two in `mlr3tuning`:

1. [TunerDesignPoints](https://github.com/mlr-org/mlr3tuning/blob/03b9bcb8344d5f19b147ec0d92154229fd067c50/R/TunerDesignPoints.R#L56) does this ostensibly for asserts but then goes on to use the internal `data.table` representation. I think this is the only possibly objectionable case.
2. [TuningInstance](https://github.com/mlr-org/mlr3tuning/blob/03b9bcb8344d5f19b147ec0d92154229fd067c50/R/TuningInstance.R#L222) converts to a `Design` and then uses that to generate `x`-points through `$transpose()`, which also does the `$trafo()` application for us. This is very much what `Design` was made for.

**Comment by berndbischl** [comment]
we have check_dt now in ParamSet
