### ISSUE TITLE
an example to make dependent tuning work

### ISSUE THREAD

**Issue by smilesun** [mlr-org/paradox#27]
If we concatenate a filterwrapper together with a tune wrapper and want to co-tune the hyper-parameters for the learner (random forest) and the fw.perc. Currently it seems to be difficult to do, since the fw.perc comes first which will select the number of features that will be fed into the tuneWraper, but the mtry parameter in random forest decides on the number of features which is variable for each iteration of the tuning.  Our new version should make this kind of tuning easier to be done. 
```
ps.ranger = function(p) { 
  makeParamSet(
    # FIXME: mtry must depend on the other parameter "fw.perc"
    # makeIntegerParam("mtry", lower = as.integer(p/10), upper = as.integer(p/1.5)),
    #makeIntegerParam("min.node.size", lower = 1L, upper = 50L, default = 5L),
    #makeIntegerParam("num.trees", lower = 100, upper = 5000, default = 500L),
    makeNumericParam("sample.fraction", lower = 0.1, upper = 1, default = 0.5),
    # makeDiscreteParam("fw.perc", values = PERF_GRID))
    makeNumericParam("fw.perc", lower = 0.001, upper = 0.8))  # feature selection percentage
}


```

**Comment by jakob-r** [comment]
If you look [here](https://github.com/mlr-org/phng#transformations) dictonary entries are only allowed within the transformation function. The is also only one transformation function for the whole ParamSet.
Accordingly in phng you would define `mtry` as a fraction in (0,1). Then you can transform `x$mtry = dict$p * x$fw.perc * x$mtry`.
That is at least how it should work.
