### ISSUE TITLE
`get_values` doesn't work for multiple tags

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/paradox#279]
I'm not 100% sure this is a bug or a missing feature but the docs do seem to suggest this is possible. `get_values` works for single tags but not for multiple (docs say `character()`). If it's not currently possible then it would be a nice feature.

Reprex:

``` r
library(paradox)
ps = ParamSet$new(
  params = list(
    ParamDbl$new("d", lower = -5, upper = 5, default = 0, tags = "a"),
    ParamFct$new("f", levels = letters[1:3], tags = "b")
  )
)
ps$values = list(d = 1, f = "a")

ps$get_values(tags = "a")
#> $d
#> [1] 1
ps$get_values(tags = "b")
#> $f
#> [1] "a"
ps$get_values(tags = c("a", "b"))
#> named list()
```

<sup>Created on 2020-05-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jakob-r** [comment]
I updated the documentation so it becomes more clear that the conditions are connected with a logical and, i.e. you only retrieve the params that have all the tags you supplied.

**Comment by RaphaelS1** [comment]
Okay thanks, but can this be opened as a feature request or has this already been discussed and dismissed?

**Comment by jakob-r** [comment]
It kind of has been discussed and I think the solution is to use `psdt = as.data.table(ps)` and then you can do all kind of logical operations. 
However `psdt` currently is missing the values, so this could be a new issue. 
Also it is a bit cumbersome to work on listcolumns as selectors:
```r
psdt[map_lgl(tags, `%in%`, c("a","b")),]
```
