### ISSUE TITLE
Param has no active binding storage_type

### ISSUE THREAD

**Issue by sumny** [mlr-org/paradox#282]
`Param` has no active binding `storage_type`, nevertheless it is documented for `Param`, because the subclasses (`ParamDbl` etc.) have it.

**Comment by jakob-r** [comment]
You could say the same about `levels`, `nlevels`, `is_bounded`, `lower` and `upper`. All are not in the base class but we expect them to be there so it would make sense to document it in `Param.R`. Problem: Sometimes they are active bindings (e.g. `levels` for Integers) and sometimes just normal fields (e.g. `levels` for Fct). Is that a problem for documentation? Could we reuse templates for fields and active bindings. Yes, right?

**Comment by sumny** [comment]
> You could say the same about `levels`, `nlevels`, `is_bounded`, `lower` and `upper`.

Yes, but currently only `storage_type` is explicitly documented as a `field` in `Param`.

Using templates for them seems like a nice idea! Should work, I'll try this.

**Comment by sumny** [comment]
Fixed in #281
