### ISSUE TITLE
allow user to set a concrete value to a Parameter

### ISSUE THREAD

**Issue by smilesun** [mlr-org/paradox#29]
I think it might be good if the user could set a value to a ParamInt for example and so he/she can set the whole hyper-paramset mannually. This feature will allow phng to be used in any R package as a option manager.

**Comment by jakob-r** [comment]
I don't understand your point. A parameter setting is just represented as a list like in `ParamHelpers`. I don't need a phng object to represent the setting `k = 3`. Therefore I can just use `par.vals = list(k = 3)`?

**Comment by jakob-r** [comment]
The principle is that that ParamSet and ParamSimple are the definitions of parameter spaces and to be seen as constant. Concrete values are just stored in lists. Therefore I don't need to assign a concrete value to a ParamSet or ParamSimple object.
If you want to store param values and "manage" them. You could do it like that

```r
ps = ...
par.vals = list(a = 1, k = 3)
ps$test(par.vals)
# TRUE

# set a new parameter
par.vals$k = 4
ps$test(par.vals)
# TRUE
```

**Comment by smilesun** [comment]
This issue is relevant to #32,
currently in R, there is no good setting package, where user could set hyperparameters when they develop their own package. I think phng should not only serve mlr but maybe to other package as well as a general settings tool? 
In this case, we need to provide the functionality that a package developer could call ps$get("paraA") instead of only get paraA from the arguments list of the function.
furthermore, they could call ps$getAvail("paraA") so they could get all possible configurations. 

what do you think ?

@jakob-r @berndbischl  @mllg

**Comment by berndbischl** [comment]
@smilesun is basically correct here, but i will open a clean issue later / soon
