### ISSUE TITLE
Feature Request: ParamInt returns value as integer

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/paradox#293]
As an example:

``` r
library(paradox) 
ps = ParamSet$new(list(ParamInt$new("int")))
ps$values$int = 2
class(ps$values$int)
#> [1] "numeric"
```

<sup>Created on 2020-08-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

It would be really nice if this automatically converted to integer, probably easiest to do so on setting as opposed to getting.

**Comment by berndbischl** [comment]
ok, will likely do this

**Comment by berndbischl** [comment]
I am not proud of my "hacky"  fix, but it works now. nums to converted to ints "on setting" them, for ParamInt
