### ISSUE TITLE
new sugar API

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/paradox#302]
paradox sugar design doc

principles:

- we build sugar on top of whats there, to make search-space definitions "leaner"
- all current code (the "programmatic" API) stays, for complex cases you are supposed to use this 
- no NSE
- simple principles, which are easy to communicate
- combinable principles

### component 1 - paramset and param def sugar 

pss, p_dbl, p_int, etc, will simply become short R functions, which abbreviate the conctructor

API:
```r
ParamSet$new(list(
  ParamDbl$new("x", lower = 1, upper = 2),
  ParamInt$new("y", lower = 1, upper = 2)
))
```

is now possible via:
```r
pss(
  p_dbl("x", 1, 2),
  p_int("y", 1, 2)
)
```

Why? Advantages:
  - pss def much shorter
Implementation:
  - trivial
How hard to understand:
  - trivial
Potential problems: 
  - none

### component 2 - to-tune-params in $values 

It is possible now to skip the search-space def for tuning, and to define tuning-info directly in the learner-values.

API:
```r
ll$param_set$values$c = to_tune() # tunes C in bounds from learner (if they are not inf)
ll$param_set$values$c = to_tune(1, 10) # tunes C in new bounds
ll$param_set$values$c = to_tune(1, 10, "dbl")  # tunes C as a "dbl" (if C had e.g. UTY type, or a different one we dislike)
```
in mlr3tuning:
In the TuningInstance,and the AutoTuner you now simply leave arg "search_space" as NULL

Advantages:
  - short, param info can be maximally reused from the learner
  - deps dont need to be specified, can be used from the learner
  - natural?
  
How hard to understand:
  - I think this is OK, you can do EITHER this, or use the normal, flexible old search-space, not both
  - I would mainly use this new system in tutorial and posts

Implementation: 
  - we set .private$values$c to small tune-token object which collects the info from $tune(1, 4)
  - PS has a new method ps$to_tune_param_set which constructs the search-space from $values / the tokens therein,
    this is what is called in mlr3tuning
  - in ps$print we show both the normal PS and the associated searchspace (if exists)

Potential problems
  - ps$values as a getter now breaks API in calling code as this now returns the new tokens, too, in the list
    (this is unavoidable in the AB)
  - but most calling-code uses ps$get_values(), which is a function and not an AB, so we can filter out the tokens (depending on a flag-arg)

### component 3 - trafo sugar

API:
  - trafos now must be composable functions
  - each PS now has a list of trafo instead of a single one
  - trafos are executed from left to right 
  - user can still set a single function (which is then upcast to a list) 
  - paradox ships a couple of commons trafos, these are actually functionals, so they return valid trafo-functions

examples:     
  `trafo_exp2(c("sigma", "C"))`: does 2^x
  `trafo_exp(c("sigma", "C", base = 3))`: does 3^x
  `trafo_switch(list(a = complex_obj_1, b = complex_obj_2)`: helps with untyped params, optimizing over complex categorical objects 
  `trafo_round("i")`: rounds doubles to ints, to enable tuners to optimize ints

```r
ps$trafo = list(trafo_exp2(c("sigma", "C")),  trafo_round("i"))
```
        
more sugar (this is also possible):
```r
ll$values$C = to_tune(-10, 10, function(x) 2^x)
ll$values$C = to_tune(-10, 10, "log2-scale")
```

Advantages:
  - trafos can be defined quickly, without complicated function (building blocks)
  - composition is nice
  - super nice: `ll$values$C = to_tune(-10, 10, "log2-scale")`

How hard to understand:
  - probably easier than before, if you only use the new system
  - list of (non-conflicting) trafo soimple to understand
  - the mapping from "shipped trafo" to "how is it implemeneted" is simple

Potential problems
  - none, due to the upcast to list

Implementations: 

- ps$private$.trafo now list (instead of a function), thats kinda it?
- we execute the list in a loop
- we need this for this sugar to work:
```r
  ll$values$C = to_tune(-10, 10, function(x) 2^x)
convert_trafo = function(pid, f) {
  force(pid)
  function(x, ps) {
    x[[pid]] = f(x[[pid]])
    return(x)
  }
}
```

**Comment by be-marc** [comment]
Different implementation merged with https://github.com/mlr-org/paradox/pull/301.
