### ISSUE TITLE
Performance Bottleneck for large ParamSetCollections

### ISSUE THREAD

**Issue by mb706** [mlr-org/paradox#303]
Apparently PSC is a bottleneck for large graphs, e.g. created with
```r
library(mlr3)
library(mlr3pipelines)
library(profvis)
profvis({GraphLearner$new(ppl("bagging", lrn("regr.featureless"), iterations = 50, averager = po("regravg")))})
```

E.g. [this line](https://github.com/mlr-org/paradox/blob/18e3bdfa5ab7524cce4078c3d021fb1667c1cd03/R/ParamSet.R#L189) should be cached. Maybe there are some other speedups we can do.

**Comment by RaphaelS1** [comment]
Not that this helps to solve the issue but just to add that in a typical bagging use-case this is probably not considered a large graph so arguably this is a high priority bug for the bagging pipeline.

**Comment by mb706** [comment]
The bagging pipeline should probably use multiplicities

**Comment by mb706** [comment]
![image](https://user-images.githubusercontent.com/15801081/90774166-4d4e5480-e2f7-11ea-9570-b424fc83f1d1.png)
