### ISSUE TITLE
Questionable naming choice is_number vs. is_numeric, is_categ vs. is_categorical

### ISSUE THREAD

**Issue by mb706** [mlr-org/paradox#306]
This code defines active bindings with very similar naming, but the naming doesn't make it clear which binding gives you what. Maybe a better choice would be `all_number`, `all_categ`.

https://github.com/mlr-org/paradox/blob/e10d7401a6ddf97672cc95bcc86022b907b36063/R/ParamSet.R#L462-L486

**Comment by be-marc** [comment]
Done. b25a7761f1892d9213c8e5d9ca121d58e16c57f5.
