### ISSUE TITLE
CI does not error on NOTEs

### ISSUE THREAD

**Issue by mb706** [mlr-org/paradox#313]
IMHO CI should show an :x: when `R CMD check` finds "possible problems", but currently they seem to be ignored:

https://github.com/mlr-org/paradox/runs/1220625261#step:13:68

![image](https://user-images.githubusercontent.com/15801081/96368007-74879d80-1151-11eb-9268-82e5df072fe8.png)

**Comment by be-marc** [comment]
Agree. Fixed by 1cfa94226e6faf5ee5d4df38b905343a216c8a07.
