### ISSUE TITLE
Bounds checks are unnecessarily strict

### ISSUE THREAD

**Issue by mb706** [mlr-org/paradox#317]
E.g. we have a parameter that announces bounds between 1 and 10, and we want to grid search tune it on a log scale. `exp(log(10))` is a bit more than 10, so the evaluation fails here, imho unnecessarily.

```r
> obj <- ObjectiveRFun$new(function(xs) xs, ParamSet$new(list(ParamDbl$new("x", 1, 10))))
> tune_ps <- ParamSet$new(list(ParamDbl$new("x", log(1), log(10))))
> tune_ps$trafo <- function(x, param_set) list(x = exp(x$x))
> oi <- OptimInstanceSingleCrit$new(obj, tune_ps, trm("none"))
> OptimizerGridSearch$new()$optimize(oi)
Error in FUN(X[[i]], ...) : 
  Assertion on 'X[[i]]' failed: x: Element 1 is not <= 10.
```
(regression because of #310)

**Comment by jakob-r** [comment]
suggestion:
`obj <- ObjectiveRFun$new(function(xs) xs, ParamSet$new(list(ParamDbl$new("x", 1, 10.001))))`
:wink:
