### ISSUE TITLE
ParamSet$get_values with options for TuneTokens

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/paradox#324]
Options:
- get all values
- get only tune tokens
- get only non tune tokens

Question: Which interface
1) `get_values(types = c("tokens", "all", "values"))` - easily extendable
2) `get_values(tokens = TRUE, values = TRUE)` - easily understood
3) ?

**Comment by berndbischl** [comment]
> 1. `get_values(types = c("tokens", "all", "values"))` - easily extendable

this

**Comment by be-marc** [comment]
Closed by #326
