### ISSUE TITLE
Constructing list of `to_tune` objects from `ParamSet` [Question]

### ISSUE THREAD

**Issue by bblodfon** [mlr-org/paradox#379]
Hi!

Is it possible to convert this `ParamSet` automatically to the list below?
```
my_ps = ps(
    lambda = p_dbl(1e-03, 10, logscale = TRUE),
    alpha  = p_dbl(0, 1))

list(lambda = to_tune(p_dbl(1e-03, 10, logscale = TRUE)),
    alpha  = to_tune(p_dbl(0, 1)))
```

**Comment by sebffischer** [comment]
This is currently not possible. 
The convenience mechanism with `ps(...)` etc. can be used to create `ParamSet`s more easily but not really the other way around.

**Comment by bblodfon** [comment]
Thanks Sebastian, I though so, just asked to make sure!
