### ISSUE TITLE
Autocompletion

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/paradox#383]
One of the things in `mlr3` that is really not user friendly in my opinion is that we don't have autocompletion for parameters. 

One way to address this would be to dynamically construct the `set_values` method of a `ParamSet` to have its arguments set to the parameter ids. For that we would either have to lock the parameters in a `ParamSet` or reconstruct the method every time a parameter is added or removed. 

What do you think @mllg @be-marc @mb706

**Comment by mb706** [comment]
mllg won't like it ;-)
