### ISSUE TITLE
Deep copy of the ParamSet

### ISSUE THREAD

**Issue by zzawadz** [mlr-org/paradox#40]
I have a problem with making the copy of the ParamSet class because it seems that does not make a real `deep` copy. See the example below:

``` r
library(paradox)
#> Loading required package: data.table

pl1 <- paradox::ParamSet$new(
  params = list(
    ParamInt$new("a"),
    ParamInt$new("b")
  )
)

pl1$params
#> $a
#> a [integer]: {-Inf, ..., Inf}
#> 
#> $b
#> b [integer]: {-Inf, ..., Inf}
pl2 = pl1$clone(deep = TRUE)

pl2list <- pl2$params
invisible(
  lapply(
    pl2list,
    function(x) x$id = paste("x", x$id, sep = ":"))
)

# new param list with renamed parameters:
# so far so good.
ParamSet$new(params = pl2list)
#> ParamSet: parset 
#> Parameters: 
#> x:a [integer]: {-Inf, ..., Inf}
#> x:b [integer]: {-Inf, ..., Inf}

# However the ids in pl1 were also changed:(
pl1
#> ParamSet: parset 
#> Parameters: 
#> x:a [integer]: {-Inf, ..., Inf}
#> x:b [integer]: {-Inf, ..., Inf}
```

The explanation appears to quite simple - R6 makes a copy of the `params` list, but not the elements in that list (I think that this behavior of R6 makes sense because it should not examine every data structure in each field to check if there's something to copy). However, in the ParamSet case, I think that all the elements of the `params` list should be copied when the `deep` parameter is set to true.

What do you think?

**Comment by berndbischl** [comment]
Very abvious. We need a deep copy

**Comment by zzawadz** [comment]
It's a bit tricky to make it right, because `ParamSetBase` evaluates `params[[i]]$handle$root = self, which will cause an infinitive recursion if we try use `deep = TRUE` in the `deep_copy` method.

**Comment by berndbischl** [comment]
ParamSet deep copies are enabled and unit tested
