### ISSUE TITLE
the "generate design" stuff should not be functions of the paramset

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/paradox#42]
doesnt really make sense and couples it too tightly

this should really go into a dedicated service class or service functions

**Comment by jakob-r** [comment]
But if you implement another ParamSet class (e. g tree stuff) you will need to S3 the function. Do you really want that?

**Comment by jakob-r** [comment]
I don't see how to apply this method in this case. Can you elaborate?
generate_grid_design stays a method of ParamSet but the function is externalized and in the construction of a ParamSet object I define which function to use for the method generate_grid_design? I don't see why we need a class `DesignGeneratorGrid`?
