### ISSUE TITLE
Function to print x values

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/paradox#43]
Function values are stored in named lists.
To transform them to a single string you could use `paste(names(x), x, sep = "=" ,collapse=",")`
This is problematic for
* Long values
* x values that can not be transferred to a character. These should not exists, because complex types are just created by transformation. But we have a untyped param class.
* Real valued numbers with many decimal places.
because they can mess up the output.

So we want to shorten and format some of them.
Formatting and shortening should be configurable.

Each ParamNode should be able to transform a named list to a character.
I propose `Param(Set/Real/...)$value_to_string(x)`.

**Comment by berndbischl** [comment]
1) old code is here:
https://github.com/berndbischl/ParamHelpers/blob/master/R/paramValueToString.R

2)> I propose `Param(Set/Real/...)$value_to_string(x)`.
dont forget the formatting options.... i think they should NOT come from R options, but an argument

**Comment by jakob-r** [comment]
Implementation is here: https://github.com/mlr-org/paradox/pull/97

**Comment by berndbischl** [comment]
@mllg currently uses as_short_string, this seems to be enough for now
--
