### ISSUE TITLE
ParamSet: do we have an "add_param" method

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/paradox#49]
matthias has this in ConfigSpace, this might be more general then adding a full list of params in construction?

**Comment by jakob-r** [comment]
we have the option to combine param sets. Should be enough?

I vote for closing this issue

**Comment by berndbischl** [comment]
no i really want this and this is necessary. 
it is more the other way around. the constructor  should either be empty or call that method, and combine should call this too

**Comment by berndbischl** [comment]
adding to a set is a really fundamental operation

**Comment by berndbischl** [comment]
should probably deep copy the param

**Comment by berndbischl** [comment]
done
