### ISSUE TITLE
Sampling of values

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/paradox#50]
should not be in paramset, and params. but seperate. 

we also need to be able flexibly implement different samplers.

this might work

A couple of mini classes like this:

PSamplerIntUnif
PSamplerNumNormal
PSamplerNumUnif
they all inherit from PSampler, implement p$sample(n)

Then we have this:
pss = ParamSetSamplerIndep$new(list of samplers)
pss$sample(10)

inherits from ParamSetSampler

**Comment by jakob-r** [comment]
New conclusion.
ParamSet has setSampler

u = UniformSampler$new()
u$new("id.of.param")
u$sample(n) -> DF
ps$setSampler(u)
ps$isDistribution() has sampler? -> T/F
