### ISSUE TITLE
Param* renaming

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/paradox#60]
"Real" is bad because of the English "real" (wirklich)

**Comment by berndbischl** [comment]
done

**Comment by mllg** [comment]
I don't like float. R uses numeric or double.

**Comment by berndbischl** [comment]
you yourself, use "flag" in checkmate

**Comment by berndbischl** [comment]
i have nothing against "Double", but "Real" was a bad name (really). 
And "Numeric" is ambigouus, as it even in in R itself.

But I want this to be resolved quickly, otherwise we have to rename in too many places

so: ParamDouble ok for you?

**Comment by berndbischl** [comment]
@mllg

**Comment by mllg** [comment]
This is what we currently have:

| paradox name | full name   | r type             |
|--------------|-------------|--------------------|
| bool         | boolean     | logical            |
| int          | integer     | integer            |
| double       | double      | double             |
| categ        | categorical | factor / character |

I don't like it.

**Comment by mllg** [comment]
We could use the type abbreviations from purrr/forcats:

| short name | r type  |
|----------------|-----|
| lgl        | logical |
| int        | integer |
| dbl        | double  |
| fct        | factor  |

**Comment by berndbischl** [comment]
> I don't like it.

fine. but we need to move forward. then post suggestions - as you did.  



> We could use the type abbreviations from purrr/forcats:

i could live with that

**Comment by berndbischl** [comment]
+1 for all having the same length and allowing better alignment

**Comment by berndbischl** [comment]
we used purrr names
