### ISSUE TITLE
please do not use InheritFrom ala copy paste in the classes

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/paradox#62]
yes, i know you wanted to have the inherited methods / and member available.

but that is simply clutterings up the roxygen docs. 
IMHO roxygen should do that for us. until it is not there, the only thing we need to provide is a link to the superclass. then users can click on that. 

i removed all of that already, i think. keep this issue simply FYI, pls close

**Comment by berndbischl** [comment]
@jakob-r  briefly read pls

**Comment by jakob-r** [comment]
acknowledged
