### ISSUE TITLE
how can we check stuff like this in checkmate

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/paradox#64]
if (sum(!is.null(resolution), !is.null(param_resolutions), !is.null(n)) != 1) {
    stop("You can only specify one of the arguments!")
  }

**Comment by mllg** [comment]
1. Why is this a paradox issue?
2. There is no function for this in checkmate.

**Comment by berndbischl** [comment]
> 1. Why is this a paradox issue?

because we have the quoted code in the package. and its bad

**Comment by berndbischl** [comment]
and if we dont have anything for this in cm, well, the bad code apparently has to stay
