### ISSUE TITLE
ParamCategorical is should be renamed to ParamCateg

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/paradox#67]
long names are not necessarily better. they are harder to type and read

**Comment by berndbischl** [comment]
done

**Comment by mllg** [comment]
Since when do we do abbreviations?

**Comment by berndbischl** [comment]
since always

**Comment by berndbischl** [comment]
oh come on. the rule is a name should be expressive, and intuitive. but not too long.
and ideal name is very short, but extremely clear.

do you really want me too google for and link to this? 
https://ac.els-cdn.com/S0167642309000343/1-s2.0-S0167642309000343-main.pdf?_tid=e075d970-6e7b-476d-a0ee-6ab8dc028068&acdnat=1543791782_fa85dbb560b5a0e59834815d5f6ac56a

The thing is, that long identifiers have obvious disadvantes. obvious. 
long lines. more typos. 
in case of doubt (if names coule be mistaken) i would rather take a longer one.

i will continue in the other thread where you have posted a table
