### ISSUE TITLE
designs / tables with categ params

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/paradox#79]
are they encoded with factors or chars?
because if we use factors, we need to ensure that levels are complete, which sucks...
@mllg

**Comment by berndbischl** [comment]
this also relates to sampling as that creates dts too

**Comment by berndbischl** [comment]
this needs to be documented NOW

**Comment by berndbischl** [comment]
otherwise we fuckup stuff downstream in other packages

**Comment by mllg** [comment]
What if you need a design with factors? Generate data.table, then iterate over the columns and parameters yourself to set the levels?

The other way around is easy, just `map_if(dt, is.factor, as.character)`.

**Comment by berndbischl** [comment]
> Generate data.table, then iterate over the columns and parameters yourself to set the levels?

yes, that is one line? and i can create a helper if you really need that? or you can create a helper yourself before i do that?

can you name at least one case where the factors are needed? 
here is one where they hurt:
what is the most often performed operation on such a table:
d = transpose(d)
map(d, algo_eval)

now factor cols become 1-el-factors. and that does not work and leads to VERY bad bugs.
why do i know that? we are in exactly the same scenario in batchtools.
remember what your answer to this problem was in batchtools? 
"do not use df objects, they create factors by default. use a dt - with characters"

so?

**Comment by mllg** [comment]
> can you name at least one case where the factors are needed?

You generate a random design and want to make sure that you've sampled all factor levels at least once.

```
> d = transpose(d)
> map(d, algo_eval)
```
You should use `pmap` (or `.mapply`). 

> now factor cols become 1-el-factors. and that does not work and leads to VERY bad bugs.

Why "does [that] not work"? Why does this lead to bugs?

> why do i know that? we are in exactly the same scenario in batchtools.
> remember what your answer to this problem was in batchtools?
> "do not use df objects, they create factors by default. use a dt - with characters"

I don't understand this argument. There are no factors in batchtools, except user input. But we are not talking about user input here, we are literally discussing the best storage type for a factor. I opt for factor, but I really don't care that much.

**Comment by berndbischl** [comment]
> There are no factors in batchtools, except user input. B

thats what we are exactly talking about here. the "user input" is a function you call. a function you dont control. in our case very often a learner. that function now is 
train_foo(hyperpar = string)
now you pass a factor. what happens is 2 cases
a) you fail the assert 
b) your factor becomes an int (and a bad bug happened)
i can probably still link to exactly that issue in batchtools

**Comment by berndbischl** [comment]
we are using chars. sorry :)
