### ISSUE TITLE
if you use for-loops over multiple objects in testthat you should use the "info" arg in expectations

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/paradox#82]
because otherwise one cannot see where a test fails..
pls do that

**Comment by berndbischl** [comment]
@jakob-r at least akowledge please

**Comment by berndbischl** [comment]
i added the infos often

**Comment by jakob-r** [comment]
acknowledged. I guess I didn't knew that argument back then, when I wrote the tests.
